<?php
//Import PHPMailer classes into the global namespace
//These must be at the top of your script, not inside a function
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

//Load Composer's autoloader (created by composer, not included with PHPMailer)
require 'vendor/autoload.php';

// Load .env file when environment variables have not been injected by the
// hosting platform (e.g. Hostinger shared hosting).
// On Render / Docker the variables are already present via the platform, so
// this block is skipped.
// ---------------------------------------------------------------------------
$envFile = __DIR__ . '/.env';
if (file_exists($envFile)) {
    $lines = file($envFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
    foreach ($lines as $line) {
        // Skip blank lines and comment lines
        $trimmed = ltrim($line);
        if ($trimmed === '' || $trimmed[0] === '#') {
            continue;
        }
        if (strpos($line, '=') === false) {
            continue;
        }
        [$key, $val] = explode('=', $line, 2);
        $key = trim($key);
        $val = trim($val);
        // Strip a matching pair of surrounding quotes, preserving inner content
        if (strlen($val) >= 2) {
            $first = $val[0];
            $last  = $val[strlen($val) - 1];
            if (($first === '"' && $last === '"') || ($first === "'" && $last === "'")) {
                $val = substr($val, 1, -1);
            }
        }
        // Do not overwrite variables already set by the platform
        if ($key !== '' && getenv($key) === false) {
            putenv("{$key}={$val}");
            $_ENV[$key] = $val;
        }
    }
}



header('Content-Type: text/plain; charset=utf-8');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo 'Method not allowed.';
    exit;
}

$firstName = htmlspecialchars(trim($_POST['firstname'] ?? ''), ENT_QUOTES, 'UTF-8');
$lastName  = htmlspecialchars(trim($_POST['lastname']  ?? ''), ENT_QUOTES, 'UTF-8');
$email     = filter_var(trim($_POST['email']    ?? ''), FILTER_VALIDATE_EMAIL);
$inquiry   = htmlspecialchars(trim($_POST['inquery']   ?? ''), ENT_QUOTES, 'UTF-8');
$message   = htmlspecialchars(trim($_POST['subject']   ?? ''), ENT_QUOTES, 'UTF-8');

if (!$firstName || !$email || !$message) {
    http_response_code(400);
    echo 'Please fill in all required fields.';
    exit;
}


// logic to handle line breaks in the message
$formattedMessage = nl2br($message);

$bodyContent = "
<div style='font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; border: 1px solid #eee; padding: 20px;'>
    <h2 style='color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px;'>New Inquiry Received</h2>
    
    <p>You have received a new message from your HEDS contact form.</p>
    
    <table style='width: 100%; border-collapse: collapse; margin-top: 20px;'>
        <tr>
            <td style='padding: 10px; background: #f9f9f9; font-weight: bold; border: 1px solid #ddd; width: 30%;'>Sender Name:</td>
            <td style='padding: 10px; border: 1px solid #ddd;'>$firstName $lastName</td>
        </tr>
        <tr>
            <td style='padding: 10px; background: #f9f9f9; font-weight: bold; border: 1px solid #ddd;'>Email Address:</td>
            <td style='padding: 10px; border: 1px solid #ddd;'><a href='mailto:$email'>$email</a></td>
        </tr>
        <tr>
            <td style='padding: 10px; background: #f9f9f9; font-weight: bold; border: 1px solid #ddd;'>Subject/Inquiry:</td>
            <td style='padding: 10px; border: 1px solid #ddd;'>$inquiry</td>
        </tr>
    </table>

    <div style='margin-top: 20px; padding: 15px; background: #fffdf5; border-left: 4px solid #f1c40f;'>
        <strong style='display: block; margin-bottom: 10px;'>Message:</strong>
        <p style='white-space: pre-wrap; line-height: 1.6;'>$formattedMessage</p>
    </div>

    <hr style='border: 0; border-top: 1px solid #eee; margin: 20px 0;'>
    <p style='font-size: 12px; color: #999;'>This email was generated by your website's contact form via AWS SES.</p>
</div>
";



$smtp_username    = getenv('SMTP_USERNAME');
$smtp_password    = getenv('SMTP_PASSWORD');
$smtp_domain = getenv('SMTP_DOMAIN');

if (!$smtp_username || !$smtp_domain) {
    http_response_code(500);
    echo 'Mail service is not configured. Please contact us directly.';
    exit;
}


//Create an instance; passing `true` enables exceptions
$mail = new PHPMailer(true);

try {
    //Server settings
    $mail->SMTPDebug = SMTP::DEBUG_OFF;                      //Enable verbose debug output
    $mail->isSMTP();                                            //Send using SMTP
    $mail->Host       = $smtp_domain;  //Set the SMTP server to send through
    $mail->SMTPAuth   = true;                                   //Enable SMTP authentication
    $mail->Username   = $smtp_username;                     //SMTP username
    $mail->Password   = $smtp_password;                               //SMTP password
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;            //Enable implicit TLS encryption
    $mail->Port       = 465;                                    //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`


    //Recipients
    $mail->setFrom('karugabamwesigwa@gmail.com', "WebVisitor: ".$firstName." ".$lastName); //Use your own verified business email (e.g., info@yourcompany.com).
    //$mail->setFrom('karugabamwesigwa@gmail.com', "WebVisitor: ".$firstName." ".$lastName); //Use your own verified business email (e.g., info@yourcompany.com).
    $mail->addAddress('support@highenddigitalservices.com', 'Admin');     //Add a recipient
    //$mail->addAddress('ellen@example.com');               //Name is optional
    $mail->addReplyTo($email, $firstName." ".$lastName); //Use the email address the customer typed into your form.

    //Content
    $mail->isHTML(true);                                  //Set email format to HTML
    $mail->Subject = $inquiry;
    $mail->Body    = $bodyContent;
    $mail->AltBody = "NEW INQUIRY\n" .
                    "--------------------------\n" .
                    "From: $firstName $lastName\n" .
                    "Email: $email\n" .
                    "Inquiry: $inquiry\n" .
                    "--------------------------\n" .
                    "Message:\n$message";

    $mail->AltBody = $mail->AltBody;

    $mail->send();
    // If it succeeds, redirect to your thank you page
    header("Location: ../frontend/thanks.php?name=" . urlencode($firstName));
    exit;
} catch (Exception $e) {
    echo "Message could not be sent. Mailer Error: {$mail->ErrorInfo}";
}
